---
title: "Jettered_Boxplot"
author: "Muhammad Zam Hazri Bin Zamri"
date: "2025-01-26"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Load required libraries
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```
# Data adjustment and loading
```{r}
# Load your expression dataset from a GCT file
gct_file <- "~/GeneExpressionAnalysis/Data/Lung Cancer/Pre-Malignant/GSE79209/79209_ssGSEA.gct"

# Read the GCT file, skipping the first two lines (header info)
expression_data <- read.table(gct_file, header = TRUE, skip = 2, row.names = 1)

# Remove the "Description" column if it exists
# Assuming "Description" is the second column in the data frame
expression_data <- expression_data[, -1]  # Remove the first column

# Remove everything after the last occurrence of '_' or '.'
colnames(expression_data) <- gsub("[_.].*$", "", colnames(expression_data))

# Load your grouping information from a CSV file
grouping_file <- "~/GeneExpressionAnalysis/Data/Lung Cancer/Pre-Malignant/GSE79209/GSE79209_samplegroup.tsv"
grouping_data <- read.table(grouping_file, header = TRUE, sep = "\t")

# Reshape the expression data to long format for ggplot
long_data <- expression_data %>%
  pivot_longer(cols = everything(), names_to = "Sample", values_to = "Expression")

# Join with grouping information based on Sample name
long_data <- left_join(long_data, grouping_data, by = "Sample")
```
# Define color palatte
```{r}
# Define start and end colors
start_color <- "#BEBEBE"
end_color <- "#FB9A99"  

# Generate (n) colors for (n) categories
color_palette <- colorRampPalette(c(start_color, end_color))(6)
```
# Plot for all sample
```{r}
# Set Condition as an ordered factor
long_data$Condition <- factor(long_data$Condition,
                              levels = c("Normal", "Hyperplasia", "Metaplasia", "Mild dysplasia", "Moderate dysplasia", "Severe dysplasia"),
                              ordered = TRUE)

# Create the box plot
ggplot(long_data, aes(x = Condition, y = Expression, fill = Condition)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  scale_fill_manual(values = setNames(color_palette, levels(long_data$Condition))) +
  labs(title = "ssGSEA GSE79209",
       x = "Group",
       y = "Expression") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "none"
  )
```
# Plot for current smoker sample
```{r}
# Filter long_data to keep only non-smoker samples
long_data_current_smoker <- long_data %>%
  filter(`Smoking.status` == "Current smoker")

# Set Condition as an ordered factor
long_data_current_smoker$Condition <- factor(long_data_current_smoker$Condition,
                              levels = c("Normal", "Hyperplasia", "Metaplasia", "Mild dysplasia", "Moderate dysplasia", "Severe dysplasia"),
                              ordered = TRUE)

# Create the box plot
ggplot(long_data_current_smoker, aes(x = Condition, y = Expression, fill = Condition)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  scale_fill_manual(values = setNames(color_palette, levels(long_data$Condition))) +
  labs(title = "ssGSEA GSE79209 (Current smoker)",
       x = "Group",
       y = "Expression") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "none"
  )
```
# Plot for former smoker sample
```{r}
# Filter long_data to keep only non-smoker samples
long_data_former_smoker <- long_data %>%
  filter(`Smoking.status` == "Former smoker")

# Set Condition as an ordered factor
long_data_former_smoker$Condition <- factor(long_data_former_smoker$Condition,
                              levels = c("Normal", "Hyperplasia", "Metaplasia", "Mild dysplasia", "Moderate dysplasia", "Severe dysplasia"),
                              ordered = TRUE)

# Create the box plot
ggplot(long_data_former_smoker, aes(x = Condition, y = Expression, fill = Condition)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  scale_fill_manual(values = setNames(color_palette, levels(long_data$Condition))) +
  labs(title = "ssGSEA GSE79209 (Former smoker)",
       x = "Group",
       y = "Expression") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "none"
  )
```